openapi: 3.0.0
info:
  title: User Authentication API
  description: API for user management with JWT authentication.
  version: 1.0.0

paths:
  /register:
    post:
      summary: Register a new user
      description: Register a new user by providing a username, an email and password. The password will be hashed before storing.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                email:
                  type: string
                  example: mail@mail.com
                password:
                  type: string
                  example: P@ssw0rd
              required:
                - username
                - password
                - email
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input data

  /login:
    post:
      summary: User login
      description: Authenticate a user by verifying the username and password, and return a JWT token if successful.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: johndoe
                password:
                  type: string
                  example: P@ssw0rd
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpYXQiOjE2MjI5NzQ4MDB9.UeQsH1oEot
        '400':
          description: Invalid credentials
